// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg9KRGawZ3KONimFjcrq_APpAq0f9hgwA',
    appId: '1:783627667505:web:078b1e0f7d0763fdc1ed10',
    messagingSenderId: '783627667505',
    projectId: 'triffy-1cc5e',
    authDomain: 'triffy-1cc5e.firebaseapp.com',
    storageBucket: 'triffy-1cc5e.appspot.com',
    measurementId: 'G-X1HVSE7QE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6rJ_sY7wNxowm3cWtpYGsxXGTNoAFac',
    appId: '1:783627667505:android:0f2b4dc822a67a13c1ed10',
    messagingSenderId: '783627667505',
    projectId: 'triffy-1cc5e',
    storageBucket: 'triffy-1cc5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdp-98Jq5AhBlFNd3NDdE__4JIrYFGO7U',
    appId: '1:783627667505:ios:08916d05379c7b60c1ed10',
    messagingSenderId: '783627667505',
    projectId: 'triffy-1cc5e',
    storageBucket: 'triffy-1cc5e.appspot.com',
    iosClientId:
        '783627667505-0tjd1c31rcvm4n0sj5pot4qm1qumetrb.apps.googleusercontent.com',
    iosBundleId: 'com.khan.triffy',
  );
}
